### ISSUE TITLE
rt or lowlatency kernel

### ISSUE THREAD

**Issue by emviveros** [linuxdeepin/deepin-kernel#10]
Hi developers..!  There's a way to have installed a kernel for realtime applications? I need that to use deepin as my distro for audio applications.

If no, some tips to apply rt patch and compile deepin kernel successfully? 

Thanks for all your work! :+1:

**Comment by floatbeta** [comment]
Depending on the kernel your distro is running so open the terminal type in uname -r and take note of the kernel vesion.

Go to https://cdn.kernel.org/pub/linux/kernel/projects/rt/ and find your kernel version and click on the link and copy the link to the packages.

wget (paste copied url)

You also need to wget the kernel deepin is using.

Unpack

xz -cd deepinkernel package | tar xvf -

cd into extracted folder

xzcat ../patchpackage | patch -p1

The only necessary configuration for real-time Linux kernel is the choice of the “Fully Preemptible Kernel” preemption model (CONFIG_PREEMPT_RT_FULL). All other kernel configuration parameters depend on system requirements. For detailed information about how to configure a kernel have a look at Linux kernel documentation.

When measuring system latency all kernel debug options should be turned off. They require much overhead and distort the measurement result. Examples for those debug mechanism are:

DEBUG_PREEMPT
Lock Debugging (spinlocks, mutexes, etc. . . )
DEBUG_OBJECTS
…
Some of those debugging mechanisms (like lock debugging) produce a randomized overhead in a range of some micro seconds to several milliseconds depending on the kernel configuration as well as on the compile options (DEBUG_PREEMPT has a low overhead compared to Lock Debugging or DEBUG_OBJECTS).

However, in the first run of a real-time capable Linux kernel it might be advisable to use those debugging mechanisms. This helps to locate fundamental problems.

Building the kernel
Building the kernel and starting the kernel works similarly to a kernel without PREEMPT_RT patch.


Go to https://wiki.linuxfoundation.org/realtime/documentation/howto/applications/preemptrt_setup for full instructions.

**Comment by emviveros** [comment]
Thanks @floatbeta!!! I will test it and post results here! :+1:

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
