### ISSUE TITLE
Bug: Crashing in Virtualbox

### ISSUE THREAD

**Issue by axelkennedal** [linuxdeepin/deepin-kernel#12]
I've installed Deepin 15.6 in Virtualbox 5.2.16 running in macOS Mojave Developer Beta. I've also installed the Virtualbox Guest Additions.

Sometimes when I tab away from the VM, do something else for a while and come back the OS has crashed, with this screen:

<img width="889" alt="skarmavbild 2018-08-12 kl 16 35 41" src="https://user-images.githubusercontent.com/8863787/44003135-619e1262-9e4e-11e8-806e-e11d12df4a46.png">

If I after this "send the shutdown signal" from Virtualbox to the machine running Deepin I get back what I was looking at before (the desktop interface reappears and everything appears to work as normal).

Please let me know if you need more information to solve this issue.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
