### ISSUE TITLE
Intel based Notebook 'freeze' after enter into 'suspension' mode

### ISSUE THREAD

**Issue by siemien** [linuxdeepin/deepin-kernel#2]
The model of notebook is ASUS F553M

**Comment by yyyeerbo** [comment]
Can you please post the log files?

**Comment by siemien** [comment]
False alarm, after updates system and kernel works just perfect, much better than Ubu kernel :)) Suspension mode works, thank you! But if you whant to see my logs, of last 5 days after install deepin OS [here you go](http://www.speedyshare.com/M4sv9/logs.zip)
