### ISSUE TITLE
System freezes randomly

### ISSUE THREAD

**Issue by siemien** [linuxdeepin/deepin-kernel#3]
All issues are described in this thread:
en.bbs.deepin.org/forum.php?mod=viewthread&tid=30717

I used Deepin newest stable version 15.2
DEVS please fix it

**Comment by siemien** [comment]
I try this kernel i hope this fix my issues : http://linuxdaddy.com/blog/install-kernel-4-4-on-ubuntu/

**Comment by yyyeerbo** [comment]
30717不是内核问题呀...

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
