### ISSUE TITLE
Why not BFQ?

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/deepin-kernel#4]
Why Deepin kernel not apply BFQ patch?

**Comment by yyyeerbo** [comment]
it is included in branch 4.4.0-3 and above. but it is not decided to release 4.4.0-3 or not

**Comment by bigbruno** [comment]
News about bfq?

Deepin have good performance, but hard drive I/O not so good and bfq maybe solve this.

**Comment by yyyeerbo** [comment]
probably not included in deepin kernel in near furture

**Comment by bigbruno** [comment]
Sorry for insistence, but BFQ have great news.

BFQ release new version with lot changes, now is easy for add in deepin kernel, because now not remove CFQ, if possible apply this patch, but not change bfq for default, that's make possible lot  of tests before make BFQ default.

Please, see how startup time decrease using BFQ:


-----------------------------------------------------------------------------
| SCHEDULER | Test |
-----------------------------------------------------------------------------
| BFQ | CFQ | DEADLINE | NOOP | |
-----------------------------------------------------------------------------
| | | | | Aggregate Throughput |
| | | | | [MB/s] |
| 399 | 400 | 400 | 400 | 10 raw seq. readers |
| 191 | 193 | 202 | 203 | 10 raw random readers |
-----------------------------------------------------------------------------
| | | | | Start-up time 10 seq |
| | | | | [sec] |
| 0.21 | >60 | 1.91 | 1.88 | xterm |
| 0.93 | >60 | 10.2 | 10.8 | oowriter |
| 0.89 | >60 | 29.7 | 30.0 | konsole |
-----------------------------------------------------------------------------
| | | | | Start-up time 10 rand |
| | | | | [sec] |
| 0.20 | 0.30 | 0.21 | 0.21 | xterm |
| 0.81 | 3.28 | 0.80 | 0.81 | oowriter |
| 0.88 | 2.90 | 1.02 | 1.00 | konsole |
-----------------------------------------------------------------------------

http://lkml.iu.edu/hypermail/linux/kernel/1610.3/02246.html

**Comment by bigbruno** [comment]
Just saying about problem, today i'm move 833 files, total size: 26,1 GB

From ssd to hdd using deepin file manager and kernel 4.8 from deepin repository.

My PC is 4790k with 32 GB of RAM, but during this transfer my pc is very slow, like i never see, locking mouse movement and keyboard.

This is a very old problem, in my actual configuration this not commonly, but in old hardware i see this problem constantly with move large files, i'm see this from my first months using Linux, more os less in 2004, and just fix for this i'm found is BFQ patch.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
