### ISSUE TITLE
snd emu10k1 module missing

### ISSUE THREAD

**Issue by toddfraser88** [linuxdeepin/deepin-kernel#5]
the snd emu10k1 module is missing from the 64-bit version of the deepin kernel, it is present in the 32-bit version

could you please fix this?

**Comment by yyyeerbo** [comment]
had_intel/ctxfi support almost all cards, do you have any special reason to use emu10k1?

**Comment by toddfraser88** [comment]
I am using an audigy rx, 
this card won't work without this module

**Comment by toddfraser88** [comment]
can this be fixed?

**Comment by yyyeerbo** [comment]
I will enable it in next release

**Comment by yyyeerbo** [comment]
I think I made a mistake, EMU10k1 depends on ZONE_DMA, which should not be enabled in amd64

so, this will be stay disabled in amd64

**Comment by toddfraser88** [comment]
> EMU10k1 depends on ZONE_DMA, which should not be enabled in amd64

why not?

at the moment, there is no sound at all for the audigy rx sound card in amd64 environments, but works fine in i686
so how might this be fixed?

**Comment by yyyeerbo** [comment]
emu10k1 and emu10k1x is enabled.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
