### ISSUE TITLE
Is this kernel curent?

### ISSUE THREAD

**Issue by horvan** [linuxdeepin/deepin-kernel#6]
Dear deepin dev Team ,

I have sean this:

https://en.bbs.deepin.org/forum.php?mod=viewthread&tid=31654

in the deepin forums.

If the user is correct your kernel needs to be updated soon.

Please take the your time to aproove this and drop him a note in the forms

Thank you in advance

A deepin fan

**Comment by yyyeerbo** [comment]
It will be released tomorrow. It take some time to test
