### ISSUE TITLE
kernel update proposal

### ISSUE THREAD

**Issue by PalinuroSec** [linuxdeepin/deepin-kernel#7]
hello, i am a Parrot core developer and i have worked to the updates of our custom kernel

i see that you have an outdated and vulnerable kernel, and i don't know if you are already at work to update it

can i contribute to deepin by pull-requesting a more recent debianized kernel to this repo? do you have any specific patch that should be applied?

if you also need help with the build process i can try to compile it for you on our build servers and send all the dscs, tarballs, debs and udebs to you (all gpg-signed and hashed)

-- let's make the world a safe place

**Comment by snyh** [comment]
Thanks .
We use gerrit to maintain the repository, so the better away is to submit a CL to [https://cr.deepin.io/#/admin/projects/kernel/deepin-kernel](url) . 

The main developer of deepin-kernel  is @yyyeerbo .

**Comment by bigbruno** [comment]
EclipseSpark, great job, you update to 4.7 kernel in testing debian repository?

I know deepin use LTS kernel, but i think this project need maintain more recent kernel, because in Linux hardware support depends of kernel updated.

**Comment by yyyeerbo** [comment]
already updated to 4.4.26.

froking from debian to build 4.8.4 now

**Comment by EclipseSpark** [comment]
ok, thanks anyway for having replied

**Comment by PalinuroSec** [comment]
i think it can be closed
