### ISSUE TITLE
CK kernel for smooth system

### ISSUE THREAD

**Issue by bigbruno** [linuxdeepin/deepin-kernel#8]
In another ISSUE I asked about BFQ, but should have gone straight to the CK patch.

This patch has been maintained for many years, and really make much difference in using the system.

In most benchmarks this is not shown, because the tests are done to identify raw performance and unresponsiveness of the system.

When the system load is too high, it is normal small jumps occur during playback of video, audio or even mouse movement and lag while typing text.

CK patch just solve this problem, and is widely used in ARCH and its derivatives distributions, such as the Manjaro, this is probably the main reason why many people consider ARCH-based distributions such as better performance.

I'm working with Linux on the desktop since 2004 and Deepin distribution is really the best there is, but I believe that some adjustments may leave the system even better.

I ask you to examine the idea carefully, is to add directly to Deepin kernel or a kernel alternate line adding -ck, it would bring a great advantage that is not adopted by other Debian-based distributions.

See the comparison of responsiveness on a computer with 12 cores and 64 GB of ram, the difference on computers with less capacity becomes larger:

Normal kernel: http://ck.kolivas.org/patches/muqss/Benchmarks/20161024/4.8.4.log

Kernel patch with CK: http://ck.kolivas.org/patches/muqss/Benchmarks/20161024/4.8.4-ck4+.log

See this also:
http://lkml.iu.edu/hypermail/linux/kernel/1610.3/04905.html

**Comment by yyyeerbo** [comment]
I was included in branch 4.4.0-3 some time ago, but never got released.

In my test, it showed some strange behavour, I cannot recall it exactly. 

Besides, the major drawback is that it didn't support cgroup..

I have not have the time to test it again 4.8.y yet, maybe better.

**Comment by bigbruno** [comment]
I know it's very difficult to make choices about kernel patch, but from what I gather the Deepin is focused on use in Desktop and therefore seems appropriate to include the -ck patches.

Regarding cgroups are not really fully supported, but at this stage the support cgroups is improved, but does not support all functions. Con Kolivas is dedicated to the improvement of performance in the Linux kernel for many years, I think very valid track your blog and evaluate in a future kernel, for example the 4.8 is not valid bring it to the Deepin.

http://ck-hack.blogspot.com.br/

I appreciate the attention, my intention is only to suggest improvements Deepin but if Deepin team believes it is better to provide the kernel without patches, I understand that every patch a kernel is something that should be analyzed very carefully.

**Comment by yyyeerbo** [comment]
4.8 is packaged only because some users want to use the latest kernel...
The transient period won't last long. The next release will probably based on next LTS

For BFS and BFQ, I myself prefer tuning parameters of CFS/CFQ to patching the kernel. however, this is not totally up to me. :)

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
