### ISSUE TITLE
Internet oscillation on Deepin 15.4

### ISSUE THREAD

**Issue by aleffsouza** [linuxdeepin/deepin-kernel#9]
Hello,

I've checked out on the system monitor and on the network history section I saw the network oscillating between N KB/s and 0 bytes/s. I just can't complete any download, sometimes I can't event access any web page... Btw everything is working fine on Windows 10 and on other devices I have.

I would appreciate some guidance about this cause I really migrated all my dev environment to Deepin and I really have loved it so far.

Regards,
Aleff Souza

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
